### ISSUE TITLE
SB-Admin-2 Rake was aborted

### ISSUE THREAD

**Issue by garycwallen** [MrPowers/frontend-generators#13] opened 2016-05-02 00:07 UTC
bundle exec rake add_assets:sb-admin-2
rake aborted!
Don't know how to build task 'add_assets:sb-admin-2' (see --tasks)
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

**Comment by MrPowers** [comment] 2016-05-06 19:28
I don't think this theme has been added to the project yet.  If you're feeling ambitious, send a pull request and I'll merge it in 😄

**Comment by toxic2302** [comment] 2016-11-07 12:23
Yeah...please add it to the project :D

**Comment by rhuberdeau** [comment] 2017-04-22 17:05
This is a duplicate of issue #2

**Closed as completed by rhuberdeau** 2017-04-22 17:05 UTC
Labels: duplicate, enhancement

**Comment by MrPowers** [comment] 2017-04-24 21:42
Thanks @rhuberdeau
